version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    restart: no
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: postgres-otomoto-compose
    restart: always
    environment:
      POSTGRES_USER: otomoto-admin
      POSTGRES_PASSWORD: otomoto-admin
      POSTGRES_DB: otomoto
