spring.application.name=AutoFinderBot
telegram.bot.token = ${TELEGRAM_BOT_TOKEN}
telegram.bot.storage.file = old
logging.level.com.example.autofinderbot = DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:db/changelog/main/db.changelog-master.yaml
liquibase.duplicateFileMode=WARN

spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
